import React, { useState, useEffect, useMemo } from 'react';
import { X, Building2, Calendar, User, AlertCircle } from 'lucide-react';
import type { Project } from '../../types/database';
import { getNextProjectCode, checkProjectCodeExists } from '../../lib/database';
import { buildFolderName } from '../../lib/naming';
import { Card, CardContent } from '../ui/Card';

interface CreateProjectModalProps {
  onClose: () => void;
  onCreate: (project: Omit<Project, 'id' | 'created_at'>) => Promise<Project>;
}

const CreateProjectModal: React.FC<CreateProjectModalProps> = ({ onClose, onCreate }) => {
  const [formData, setFormData] = useState({
    name: '',
    client: '',
    project_code: '',
    project_type: 'passive_fire' as const,
    region: 'auckland' as const,
    bwof: false,
    start_date_target: '',
    status: 'await_pre_let' as const
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [loadingCode, setLoadingCode] = useState(false);
  const [codeExists, setCodeExists] = useState(false);
  const [suggestedCode, setSuggestedCode] = useState('');
  const [customTitle, setCustomTitle] = useState('');
  const [isCustomTitle, setIsCustomTitle] = useState(false);

  useEffect(() => {
    const fetchNextCode = async () => {
      setLoadingCode(true);
      try {
        const nextCode = await getNextProjectCode(formData.region);
        setFormData(prev => ({ ...prev, project_code: nextCode }));
        setSuggestedCode(nextCode);
      } catch (err) {
        console.error('Error fetching next project code:', err);
      } finally {
        setLoadingCode(false);
      }
    };

    fetchNextCode();
  }, [formData.region]);

  useEffect(() => {
    const checkCode = async () => {
      if (!formData.project_code) {
        setCodeExists(false);
        return;
      }

      try {
        const exists = await checkProjectCodeExists(formData.project_code);
        setCodeExists(exists);

        if (exists) {
          const nextCode = await getNextProjectCode(formData.region);
          setSuggestedCode(nextCode);
        }
      } catch (err) {
        console.error('Error checking project code:', err);
      }
    };

    const debounceTimer = setTimeout(checkCode, 500);
    return () => clearTimeout(debounceTimer);
  }, [formData.project_code, formData.region]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (codeExists) {
      setError('Project code already exists. Please use the suggested code or enter a different one.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      await onCreate({ ...formData, project_title: projectTitle, is_small_project: false });
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create project');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field: string, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const useSuggestedCode = () => {
    setFormData(prev => ({ ...prev, project_code: suggestedCode }));
    setCodeExists(false);
  };

  const autoGeneratedTitle = useMemo(() => {
    return buildFolderName(formData.name, formData.client, formData.project_code);
  }, [formData.name, formData.client, formData.project_code]);

  const projectTitle = isCustomTitle ? customTitle : autoGeneratedTitle;

  // Update custom title when auto-generated title changes (if not manually edited)
  useEffect(() => {
    if (!isCustomTitle) {
      setCustomTitle(autoGeneratedTitle);
    }
  }, [autoGeneratedTitle, isCustomTitle]);

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl p-6 w-full max-w-md">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-bold text-gray-900">Create New Project</h2>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <Building2 className="w-4 h-4 inline mr-2" />
              Project Name
            </label>
            <input
              type="text"
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              placeholder="Enter project name"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <User className="w-4 h-4 inline mr-2" />
              Client Name
            </label>
            <input
              type="text"
              value={formData.client}
              onChange={(e) => handleInputChange('client', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              placeholder="Enter client name"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Project Code
            </label>
            <input
              type="text"
              value={formData.project_code}
              onChange={(e) => handleInputChange('project_code', e.target.value)}
              className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent ${
                codeExists ? 'border-red-300 bg-red-50' : 'border-gray-300'
              }`}
              placeholder="Enter project code (optional)"
              disabled={loadingCode}
            />
            {codeExists && (
              <Card variant="warning" className="mt-2">
                <CardContent>
                  <div className="flex items-start">
                    <AlertCircle className="w-4 h-4 text-yellow-600 mr-2 mt-0.5 flex-shrink-0" />
                    <div className="flex-1">
                      <p className="text-sm text-yellow-800 mb-2">
                        This project code already exists. Use suggested code: <strong>{suggestedCode}</strong>
                      </p>
                      <button
                        type="button"
                        onClick={useSuggestedCode}
                        className="text-sm bg-yellow-600 hover:bg-yellow-700 text-white px-3 py-1 rounded transition-colors"
                      >
                        Use {suggestedCode}
                      </button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>

          {projectTitle && (
            <Card variant="info">
              <CardContent>
                <label className="block text-sm font-medium text-brp-primary mb-2">
                  Project Title (Auto-generated)
                </label>
                <input
                  type="text"
                  value={customTitle}
                  onChange={(e) => {
                    setCustomTitle(e.target.value);
                    setIsCustomTitle(true);
                  }}
                  onBlur={() => {
                    // If user clears the field, revert to auto-generated
                    if (!customTitle.trim()) {
                      setCustomTitle(autoGeneratedTitle);
                      setIsCustomTitle(false);
                    }
                  }}
                  className="w-full px-3 py-2 border border-blue-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent font-mono text-sm"
                  placeholder="Edit project title"
                />
                {isCustomTitle && customTitle !== autoGeneratedTitle && (
                  <p className="text-xs text-brp-primary mt-1">Custom title - Original: {autoGeneratedTitle}</p>
                )}
              </CardContent>
            </Card>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Project Type
            </label>
            <select
              value={formData.project_type}
              onChange={(e) => handleInputChange('project_type', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              required
            >
              <option value="passive_fire">Passive Fire</option>
              <option value="intumescent">Intumescent</option>
              <option value="passive_intumescent">Passive & Intumescent</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Region
            </label>
            <select
              value={formData.region}
              onChange={(e) => handleInputChange('region', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              required
            >
              <option value="auckland">Auckland</option>
              <option value="wellington">Wellington</option>
            </select>
          </div>

          <div>
            <label className="flex items-center text-sm font-medium text-gray-700">
              <input
                type="checkbox"
                checked={formData.bwof}
                onChange={(e) => handleInputChange('bwof', e.target.checked)}
                className="w-4 h-4 mr-2 text-blue-600 border-gray-300 rounded focus:ring-2 focus:ring-brp-primary"
              />
              BWOF
            </label>
            <p className="text-xs text-gray-500 mt-1 ml-6">Building Warrant of Fitness (Skips stages 1-3)</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <Calendar className="w-4 h-4 inline mr-2" />
              Target Start Date
            </label>
            <input
              type="date"
              value={formData.start_date_target}
              onChange={(e) => handleInputChange('start_date_target', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Project Status
            </label>
            <select
              value={formData.status}
              onChange={(e) => handleInputChange('status', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
            >
              <option value="await_pre_let">Await Pre-let (Verbal confirmation)</option>
              <option value="awarded">Awarded</option>
              <option value="in_progress">In Progress</option>
              <option value="live">Live</option>
              <option value="closed">Close Project</option>
            </select>
          </div>

          {error && (
            <Card variant="risk">
              <CardContent>
                <p className="text-red-800 text-sm">{error}</p>
              </CardContent>
            </Card>
          )}

          <div className="flex space-x-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-brp-primary hover:bg-brp-primaryHover text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Creating...' : 'Create Project'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateProjectModal;