import React, { useState, useMemo, useEffect } from 'react';
import { X, Building2, Calendar, User, Mail, Phone } from 'lucide-react';
import type { Project } from '../../types/database';
import { buildFolderName } from '../../lib/naming';
import { Card, CardContent } from '../ui/Card';

interface EditProjectModalProps {
  project: Project;
  onClose: () => void;
  onUpdate: (projectId: string, updates: Partial<Omit<Project, 'id' | 'created_at'>>) => Promise<void>;
}

const EditProjectModal: React.FC<EditProjectModalProps> = ({ project, onClose, onUpdate }) => {
  const [formData, setFormData] = useState({
    name: project.name,
    client: project.client,
    project_code: project.project_code || '',
    project_type: project.project_type || 'passive_fire',
    region: project.region || 'auckland',
    bwof: project.bwof || false,
    start_date_target: project.start_date_target,
    status: project.status,
    site_manager: project.site_manager || '',
    qs: project.qs || '',
    client_qs_name: project.client_qs_name || '',
    client_qs_number: project.client_qs_number || '',
    client_qs_email: project.client_qs_email || ''
  });

  const autoGeneratedTitle = useMemo(() => {
    return buildFolderName(formData.name, formData.client, formData.project_code);
  }, [formData.name, formData.client, formData.project_code]);

  const [customTitle, setCustomTitle] = useState(project.project_title || autoGeneratedTitle);
  const [isCustomTitle, setIsCustomTitle] = useState(!!project.project_title && project.project_title !== buildFolderName(project.name, project.client, project.project_code || ''));

  const projectTitle = isCustomTitle ? customTitle : autoGeneratedTitle;

  // Update custom title when auto-generated title changes (if not manually edited)
  useEffect(() => {
    if (!isCustomTitle) {
      setCustomTitle(autoGeneratedTitle);
    }
  }, [autoGeneratedTitle, isCustomTitle]);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      await onUpdate(project.id, {
        ...formData,
        project_title: projectTitle,
        site_manager: formData.site_manager || null,
        qs: formData.qs || null,
        client_qs_name: formData.client_qs_name || null,
        client_qs_number: formData.client_qs_number || null,
        client_qs_email: formData.client_qs_email || null
      });
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update project');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field: string, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-2xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-bold text-gray-900">Edit Project</h2>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                <Building2 className="w-4 h-4 inline mr-2" />
                Project Name
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => handleInputChange('name', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                placeholder="Enter project name"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                <User className="w-4 h-4 inline mr-2" />
                Client Name
              </label>
              <input
                type="text"
                value={formData.client}
                onChange={(e) => handleInputChange('client', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                placeholder="Enter client name"
                required
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Project Code
            </label>
            <input
              type="text"
              value={formData.project_code}
              onChange={(e) => handleInputChange('project_code', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              placeholder="Enter project code (optional)"
            />
          </div>

          {projectTitle && (
            <Card variant="info">
              <CardContent className="bg-blue-50">
                <label className="block text-sm font-medium text-brp-primary mb-2">
                  Project Title (Auto-generated)
                </label>
                <input
                  type="text"
                  value={customTitle}
                  onChange={(e) => {
                    setCustomTitle(e.target.value);
                    setIsCustomTitle(true);
                  }}
                  onBlur={() => {
                    // If user clears the field, revert to auto-generated
                    if (!customTitle.trim()) {
                      setCustomTitle(autoGeneratedTitle);
                      setIsCustomTitle(false);
                    }
                  }}
                  className="w-full px-3 py-2 border border-blue-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent font-mono text-sm"
                  placeholder="Edit project title"
                />
                {isCustomTitle && customTitle !== autoGeneratedTitle && (
                  <p className="text-xs text-brp-primary mt-1">Custom title - Original: {autoGeneratedTitle}</p>
                )}
              </CardContent>
            </Card>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Project Type
              </label>
              <select
                value={formData.project_type}
                onChange={(e) => handleInputChange('project_type', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                required
              >
                <option value="passive_fire">Passive Fire</option>
                <option value="intumescent">Intumescent</option>
                <option value="passive_intumescent">Passive & Intumescent</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Region
              </label>
              <select
                value={formData.region}
                onChange={(e) => handleInputChange('region', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                required
              >
                <option value="auckland">Auckland</option>
                <option value="wellington">Wellington</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Site Manager (SM)
              </label>
              <select
                value={formData.site_manager}
                onChange={(e) => handleInputChange('site_manager', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              >
                <option value="">Select site manager</option>
                <option value="Alfie">Alfie</option>
                <option value="Ali">Ali</option>
                <option value="Chris">Chris</option>
                <option value="Karel">Karel</option>
                <option value="Zach">Zach</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                QS (Quantity Surveyor)
              </label>
              <select
                value={formData.qs}
                onChange={(e) => handleInputChange('qs', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              >
                <option value="">Select QS</option>
                <option value="Carna">Carna</option>
                <option value="Contracts">Contracts</option>
                <option value="Denver">Denver</option>
                <option value="Reynier">Reynier</option>
              </select>
            </div>
          </div>

          <div>
            <label className="flex items-center text-sm font-medium text-gray-700">
              <input
                type="checkbox"
                checked={formData.bwof}
                onChange={(e) => handleInputChange('bwof', e.target.checked)}
                className="w-4 h-4 mr-2 text-blue-600 border-gray-300 rounded focus:ring-2 focus:ring-brp-primary"
              />
              BWOF
            </label>
            <p className="text-xs text-gray-500 mt-1 ml-6">Building Warrant of Fitness (Skips stages 1-3)</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <Calendar className="w-4 h-4 inline mr-2" />
              Target Start Date
            </label>
            <input
              type="date"
              value={formData.start_date_target}
              onChange={(e) => handleInputChange('start_date_target', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Project Status
            </label>
            <select
              value={formData.status}
              onChange={(e) => handleInputChange('status', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
            >
              <option value="await_pre_let">Await Pre-let (Verbal confirmation)</option>
              <option value="awarded">Awarded</option>
              <option value="in_progress">In Progress</option>
              <option value="live">Live</option>
              <option value="closed">Close Project</option>
            </select>
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-gray-900 mb-3">Client QS Information</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <User className="w-4 h-4 inline mr-2" />
                  Client QS Name
                </label>
                <input
                  type="text"
                  value={formData.client_qs_name}
                  onChange={(e) => handleInputChange('client_qs_name', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                  placeholder="Enter client QS name"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Phone className="w-4 h-4 inline mr-2" />
                  Number
                </label>
                <input
                  type="tel"
                  value={formData.client_qs_number}
                  onChange={(e) => handleInputChange('client_qs_number', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                  placeholder="Enter phone number"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Mail className="w-4 h-4 inline mr-2" />
                  Email Address
                </label>
                <input
                  type="email"
                  value={formData.client_qs_email}
                  onChange={(e) => handleInputChange('client_qs_email', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brp-primary focus:border-transparent"
                  placeholder="Enter email address"
                />
              </div>
            </div>
          </div>

          {error && (
            <Card variant="risk">
              <CardContent className="bg-red-50">
                <p className="text-red-800 text-sm">{error}</p>
              </CardContent>
            </Card>
          )}

          <div className="flex space-x-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-brp-primary hover:bg-brp-primaryHover text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Updating...' : 'Update Project'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default EditProjectModal;